### ISSUE TITLE
Disable wrapping in tableviewer

### ISSUE THREAD

**Issue by mhkuu** [proycon/clam#27]
Would it be an idea to disable wrapping in the SimpleTableViewer? Or add a setting in the API?
An example use case is disabling sentences and values for that sentence in a tableviewer. Currently browsers will wrap then wrap the text.

**Comment by proycon** [comment]
I assume you mean the word wrap in the cells of the table viewer? You'd rather have it unwrapped and people scrolling horizontally?

**Comment by mhkuu** [comment]
This of course depends on what's in the column. In T-Scan we have one column that contains the original sentence, and there I would love to have some control over the width of that column (either with disabling wordwrap or custom CSS). I see you added both those options in recent commits, so I think this can be closed! Thanks a lot (again)! :+1:
