### ISSUE TITLE
Problem with XSLTViewer in Python 2, missing import

### ISSUE THREAD

**Issue by mhkuu** [proycon/clam#46]
I'm using CLAM in Python 2 and I think I found a bug; in [`clam/common/viewers.py`](https://github.com/proycon/clam/blob/de23a08e9c6599a21d2cea94f45bec38f16c92de/clam/common/viewers.py#L136) there's a if-else-branch that will use `BytesIO` if the `sys.version` is < 3 and `lines[0]` is a `str`, but `BytesIO` is not imported. Changing this occurrence to `StringIO` seems to resolve the issue. 

There's another occurrence of this a few lines later. If you want I can make a pull request.

**Comment by proycon** [comment]
Well spotted, I think the above commit should fix it.
