### ISSUE TITLE
Implement get() for CLAMData?

### ISSUE THREAD

**Issue by mhkuu** [proycon/clam#50]
Maybe this is already possible, but it would be nice to be able to use Python's dictionary method [get()](https://docs.python.org/2/library/stdtypes.html#dict.get) (with a default if the key is not found) for CLAMData, so that you can put e.g. 

```python
clamdata.get('test', 1.23)
```

instead of

```python
test = 1.23
if 'test' in clamdata:
     test = clamdata['test']
```

or something equivalent. Maybe by subclassing [Mapping](https://docs.python.org/2/library/collections.html?highlight=mapping#collections.Mapping)?

**Comment by proycon** [comment]
Sounds like a good idea yeah!

**Comment by mhkuu** [comment]
OK, I'll create a pull request soon!
