### ISSUE TITLE
[Safari/mac] White screen instead of 'processing' screen

### ISSUE THREAD

**Issue by martinreynaert** [proycon/clam#56]
Observed in https://ticclops.uvt.nl/vector/ and https://ticclops.uvt.nl/ticclops/ (CLAM v2.1.9), also at INT http://ticclops.clarin.inl.nl/nld/ (CLAM v0.9.13): instead of the 'processing screen' which should appear after the START button is hit, the screen turns all white leaving the user in the dark about what is happening. The normal screen(s) never return(s). Processing does continue, however.

**Comment by proycon** [comment]
Can't reproduce on firefox/linux, so sounds like a client issue? What browser/version are you on? Does it persist on another?

**Comment by martinreynaert** [comment]
Seems to be a browser problem, indeed. I get it in Safari under Mac OS, not in Chrome or Firefox. Sorry about this wild goose! I will close this issue.

**Comment by proycon** [comment]
Well, still not really invalid if we want to properly support Safari (not one of my common testing choices). But I guess this is a pretty low priority issue for now then as it has relatively few users and we don't have the mac developers to test..

**Comment by proycon** [comment]
Old issue, probably solved in the meantime, haven't gotten any further reports so closing this
