### ISSUE TITLE
clamservice checks memfree, not memavailable

### ISSUE THREAD

**Issue by bloemj** [proycon/clam#64]
clamservice performs its memory check by reading the value of memfree, which is typically quite low because modern OSes use most memory for caching. My memfree is basically never more than 1 GB, which is the requirement to spawn processes. Therefore, any clam service that spawns a process fails for me because I have less than 1GB memfree. It would be better to check memavailable, which more accurately represents what memory can be used (29 GB, in my case).

**Comment by proycon** [comment]
Fixed by OP himself ;)
