### ISSUE TITLE
Clam treats server subdirectory as project directory?

### ISSUE THREAD

**Issue by pdekker12** [proycon/clam#68]
I am using clam inside the LaMachine distribution, for the PICCL pipeline. 
I configured the server URL as https://my.server.com/piccl. However, when I open this URL, I get the error:
`
Project piccl was not found for user my.user@university.edu
`

Apparently, the subdirectory of the server, where the PICCL pipeline is hosted, is seen as a project directory. Since I cannot find other server settings that changed, I think this could be caused by recent changes in clam. In a previous LaMachine install, I had clam version 2.3, which worked well. In a new LaMachine install, with clam version 2.3.2, the problem occurs.

**Comment by proycon** [comment]
I indeed made some changes recently for more flexible URLs. I'll have to look into this, possibly a regression bug.

This is using your setup with Apache rather than the default nginx in LaMachine I assume, right?
and ``URLPREFIX`` is properly set to ``piccl`` in the service configuration file?

**Comment by proycon** [comment]
I just released v2.3.3 with an added ``INTERNALURLPREFIX`` parameter (you can set this in your service configuration file; python or yaml). It should only be in situations where this bug occurs (I still can't reproduce it). The value should be equal to the value for ``URLPREFIX``. I hope this solves this issue.

**Comment by proycon** [comment]
(please reopen if problem persists with new clam)

**Comment by pdekker12** [comment]
Thanks for looking into this and for your fix! Eventually, it looks like the error was not directly related to clam, but to our Apache piccl configuration. Previously, the following line worked:
`WSGIScriptAlias /piccl {{wsgi_dir}}/picclservice.wsgi/piccl`
Probably some code in LaMachine changed, now we had to change this line to:
`WSGIScriptAlias /piccl {{wsgi_dir}}/picclservice.wsgi`
With this configuration, everything works.
