### ISSUE TITLE
Link to flatviewer does not work

### ISSUE THREAD

**Issue by peterdekker** [proycon/clam#75]
When viewing output in the web interface (CLAM in local LaMachine installation), the Download link for an output file works, but the Flat link does not work:

It links to:
SERVER/PROJECTNAME/output/HuygensING-beaufort-1-1_0cea93b9-5c1b-4873-9498-b34c30f06780.xml.frogged.folia.xml/flatviewer
But this redirects us to the CLARIN login again (although we are logged in). Any clues?

**Comment by proycon** [comment]
It should redirect to the flaturl configured in your piccl external configuration file (the yaml file). Possibly your authentication middleware intercepts it for some reason?

**Comment by pdekker12** [comment]
Thanks, Imisinterpreted this config option: set it to our server, but should remain the RU Flat instance.
After resetting it to the RU Flat instance, I got an error from Flat, for this output file:
[HuygensING-beaufort-1-1_0cea93b9-5c1b-4873-9498-b34c30f06780.xml.frogged.folia.txt](https://github.com/proycon/clam/files/3148379/HuygensING-beaufort-1-1_0cea93b9-5c1b-4873-9498-b34c30f06780.xml.frogged.folia.txt)

Error:
```
Unexpected response from FLAT (HTTP 403, target was https://flat.science.ru.nl):
Uploaded file is no valid FoLiA Document: Start tag expected, '<' not found, line 1, column 1 (, line 1)Traceback (most recent call last): -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/foliadocserve/foliadocserve.py", line 940, in upload -- doc = folia.Document(string=data,setdefinitions=self.docstore.setdefinitions, loadsetdefinitions=True, autodeclare=True, allowadhocsets=True, processor=mainprocessor) -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/main.py", line 6999, in __init__ -- self.parsexml(self.tree.getroot()) -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/main.py", line 8147, in parsexml -- self.parsemetadata(subnode) -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/main.py", line 8039, in parsemetadata -- self.parsexmldeclarations(declarations) -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/main.py", line 7450, in parsexmldeclarations -- self.declare(type, set, **subnode.attrib) -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/main.py", line 7534, in declare -- self.setdefinitions[set] = SetDefinition(set,verbose=self.verbose) #will raise exception on error -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/foliaset.py", line 285, in __init__ -- tree = xmltreefromstring(data) -- File "/var/www/lamachine2/weblamachine/lib/python3.5/site-packages/folia/foliaset.py", line 234, in xmltreefromstring -- return ElementTree.parse(BytesIO(s), ElementTree.XMLParser(collect_ids=False)) -- File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse -- File "src/lxml/parser.pxi", line 1857, in lxml.etree._parseDocument -- File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument -- File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc -- File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc -- File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc -- File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult -- File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError -- File "", line 1 -- lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by proycon** [comment]
You could set it to your server if you deploy FLAT as well (it's in LaMachine after all), but point to us is fine too of course.

I'm a bit puzzled by the error, clearly what gets uploaded is not the contents of the file you provided, the document validates fine.

**Comment by pdekker12** [comment]
Maybe it is the login on FLAT which blocks the XML content?? Because if I just go to https://flat.science.ru.nl/, I see a login window.

Regarding the local FLAT on our server, maybe that is a good option, is it automatically served at a URL?

**Comment by proycon** [comment]
The login is bypassed, FLAT has a special unauthenticated public upload mode.

It's automatically served at ``/flat`` in a standard LaMachine installation. (but you might have constrained your installation to only do PICCL?)

**Comment by pdekker12** [comment]
I think our installation is constrained (`--install piccl` option passed to the bootstrap script). I would prefer to use the RU version of FLAT, installing a local version might bring in new problems.

Could you reproduce our problem with RU FLAT? Which other information could we give to help diagnose the problem?

**Comment by pdekker12** [comment]
Maybe PICCL sends a file link to FLAT, which it can't open, because the file is behind CLARIN authentication?

In order to prevent further problems, we would prefer to disable FLAT, so no links to FLAT are generated in the UI, also not if you click on the file name. Is this possible, is there a config option to do this?

**Comment by proycon** [comment]
CLAM actively uploads the file, so the CLARIN authentication shouldn't be an issue.

There's no option in the yaml file to disable FLAT yet,  but I'll implement that.
