### ISSUE TITLE
XML Response not terminated with \n

### ISSUE THREAD

**Issue by Warmduscher** [proycon/clam#76]
I'm calling CLAM by an HTTP-Implementation from Apache NiFi's HTTPInvoke. From time to time, the Invoke Method fails when reading the XML Response from clam. As it turn's out, the length of the Response inside the HTTP-Header given back is one byte longer than the actual content. From my point of view, the XML-Response should be terminated with a \n. If for example i'll force uwsgi to add a \n: `route = .* send-crnl:` the response is in line with the HTTP-Header.

**Comment by proycon** [comment]
Interesting issue! I haven't come across such a problem yet (and I wonder the fault is not actually in some middleware here), but I can of course easily make sure that CLAM XML responses always end in a newline if that helps resolve it.

**Comment by Warmduscher** [comment]
personally. i found a workaround i can live with. I thought that maybe others run into the same issue and might find this information useful. Of course, it would be best if you could implement this directly.

BTW: Thx for making CLAM, will certainly help me preprocess some 2M files

**Comment by Warmduscher** [comment]
as stated in my other issue, the above workaround is not working as intended. But i could resolve my issue with NiFis HTTPInvoke. So closing this as unneeded
