### ISSUE TITLE
HTTP Status Code always 200

### ISSUE THREAD

**Issue by Warmduscher** [proycon/clam#77]
While trying to implement some error handling, i wanted to check the HTTP-Statuscode for any error first, before looking inside the XML-Response from CLAM. Unfortunately this code is always given back as 200, even if the response states otherwise:

```
curl -i -k -X POST http://127.0.0.1:8080
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 16 May 2019 12:15:45 GMT
Transfer-Encoding: chunked
Connection: keep-alive

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```
i'm using nginx in front of uwsgi as in the start_production.sh

**Comment by proycon** [comment]
Strange, just a wild guess; did you enable "manage-script-name = yes" in the uwsgi ini for the webservice? I know nginx needs that (but I'm not sure if that even related to this). I assume the relevant portion of your nginx.conf has something like this?

```
location /static { alias /data2/dev/lib/python3.7/site-packages/clam/static; }
location / { try_files $uri @webservice; }
location @webservice {
    include uwsgi_params;
    uwsgi_pass 127.0.0.1:8080;
}
```

**Comment by Warmduscher** [comment]
just found out: it's my workaround for the other issue. This line in `uwsgi.ini` is causing the problem:

`route = .* send-crnl:`

sorry for keeping you busy.
