### ISSUE TITLE
API accepts file upload on finished project

### ISSUE THREAD

**Issue by Warmduscher** [proycon/clam#78]
The REST API accepts new files to be uploaded on a project which is finished. While this isn't possible on the webinterface, this can make using the API a little messy. It's more likely a usage issue than a real problem. Tough having CLAM throwing an 403 with a proper error message would be nice.

**Comment by proycon** [comment]
Sorry for the delay and thanks for the report, you're right, it should indeed return a 403. I'll look into it.
