### ISSUE TITLE
Notification when task is finished?

### ISSUE THREAD

**Issue by pboot** [proycon/clam#80]
Would it be possible to add an option for (presumably e-mail) notification when a task is finished? Then the user doesn't need to check the running processes every once in a while.

**Comment by proycon** [comment]
That might be an interesting idea yes, I'll consider it. It would require outgoing e-mail to be configured though.

**Comment by proycon** [comment]
I'm not going to implement this but leaving it up to clients to handle it. As CLAM is fairly agnostic of authentication backends, it has no obvious way of getting the user's email address.
