### ISSUE TITLE
can not use clamnewproject

### ISSUE THREAD

**Issue by zhou0** [proycon/clam#90]
[lzhou@localhost clam]$ clamnewproject contract
WARNING: You are not inside a Python Virtual Environment, using one is strongly recommended
Traceback (most recent call last):
  File "/usr/local/bin/clamnewproject", line 11, in <module>
    load_entry_point('CLAM==3.0.12', 'console_scripts', 'clamnewproject')()
  File "/usr/local/lib/python3.7/site-packages/clam/clamnewproject.py", line 54, in main
    while yn.strip().lower() not in ('y','yes','n','no'):
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by proycon** [comment]
Thanks for the report! There was indeed a bug in the script in certain environments, I now corrected it in the latest release of CLAM (v3.0.13), so it should be fixed now after you update CLAM.
